name: autoint-stpp
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.10.* 
  - pip
  - poetry=1.*
  - conda-lock=1.*
  - pytorch::pytorch=1.13.*
  - pytorch::pytorch-cuda=11.*
