name: autoint
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9.*  # or don't specify the version and use the latest stable Python
  - mamba
  - pip
  - poetry=1.*
  - pytorch::pytorch=1.12.1
platforms:
  - linux-64
