apiVersion: batch/v1
kind: Job
metadata:
  name: cuboid
  namespace: deep-forecast
  labels:
    user: zihao 
spec:
  template:
    metadata:
      labels:
        user: zihao
    spec:
      containers:
      - name: gpu-container
        image: gitlab-registry.nrp-nautilus.io/zihaozhou/autoint:latest
        command:
        - conda
        - run
        - -n
        - autoint-stpp
        - /bin/bash
        - -c
        - ssh-keyscan -t ecdsa -p 30622 -H gitlab-ssh.nrp-nautilus.io > /root/.ssh/known_hosts;
          git fetch --all --prune;
          git reset --hard origin/main;
          rm -rf ./configs; cp -r --no-preserve=mode,ownership /configs ./configs;
          echo "conda activate autoint-stpp" >> ~/.bashrc;
          aim init;
          PYTHONPATH=src python src/experiment/run_cuboid.py -c configs/prodnet_cuboid_sine.yaml --trainer.devices '[0]' --trainer.fast_dev_run true --trainer.logger False;
          mkdir -p ~/ray_results;
          sleep 5;
          PYTHONPATH=src python src/tune.py -c configs/tune_prodnet_config.yaml > ~/ray_results/stdout && make upload_results
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /configs
          name: autoint-configs
        - mountPath: /home/jovyan/.s3cfg
          subPath: .s3cfg
          name: autoint-s3cfg
        resources:
          limits:
            nvidia.com/gpu: "4"
            memory: "80G"
            cpu: "16"
          requests:
            nvidia.com/gpu: "4"
            memory: "40G"
            cpu: "12"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONIOENCODING
          value: "UTF-8"
      imagePullSecrets:
      - name: autoint-read-registry
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              # - matchExpressions:
              #   - key: kubernetes.io/hostname
              #     operator: In
              #     values:
              #     - fiona-1.famu.edu
              - matchExpressions:
                - key: nvidia.com/gpu.product
                  operator: NotIn
                  values:
                  - NVIDIA-A100-PCIE-40GB
              - matchExpressions:
                - key: nvidia.com/gpu.product
                  operator: NotIn
                  values:
                  - NVIDIA-A100-PCIE-80GB
      volumes:
        - name: autoint-vol
          persistentVolumeClaim:
            claimName: autoint-vol
        - name: autoint-configs
          configMap:
            name: autoint-configs
        - name: autoint-s3cfg
          configMap:
            name: autoint-s3cfg
        - name: dshm
          emptyDir:
            medium: Memory
