seed_everything: 1551
trainer:
    precision: 32
    max_epochs: 50
    # fast_dev_run: True
    accelerator: 'cuda'
    logger: 
        class_path: 
            aim.pytorch_lightning.AimLogger
        init_args: 
            experiment: 'autoint_stpp'
    log_every_n_steps: 1
model:
    class_path:
        models.lightning.autoint_stpp.AutoIntSTPointProcess
    init_args:
        n_prodnet: 4
        learning_rate: 0.004
data:
    class_path:
        data.lightning.sliding_window.SlidingWindowDataModule
    init_args:
        batch_size: 128
        num_workers: 8
        name: earthquakes_jp
        option: download