dataloader:
  batch_size: [128]
  sampling_density: 1024
  regenerate: false
model:
  act: ['sine', 'requ']
  n_layers: [2, 3]
  hid_dim: [64, 128]
  inp_dim: 3
  out_dim: 1
trained_model:
  retrain: false
  loss_func: ['integral_mse_loss', 'gradient_mse_loss']
