dataloader:
  batch_size: [128]
  sampling_density: 1024
  regenerate: false
model:
  act: ['reflectexp']
  # posmix: ['posmixsine']
  n_layers: [2]  # [2, 3]
  hid_dim: [128]  # [64, 128]
  inp_dim: 3
  out_dim: 1
  bias: true
trained_model:
  retrain: true
  loss_func: ['gradient_mse_loss']  # ['integral_mse_loss', 'gradient_mse_loss']
  lr: 0.005
  project: true
