benchmark:
  derivative: ['warmup', 'mixed', 'univariate', 'half-mixed']  # warmup is same as uni-, but result ignored
  computation: ['forward', 'backward']
  rerun: true
model:
  act: 'sine'  # sine is the only available act for higher order
  n_layers: [2, 3, 4]
  hid_dim: 128
  inp_dim: 7
  out_dim: 1
orders: [1, 2, 3, 4, 5, 6, 7]
n_repeat: 100
model_types: ['baseline', 'model', 'mix1', 'mix2', 'mix3', 'mix4']
