dataloader:
  name: ['covid_nj_cases']
model:
  act: ['requ']
  n_layers: [3]
  hid_dim: [128]
  inp_dim: 3
  out_dim: 1
trained_model:
  name: ['auto-stpp']
  lr: 0.0004
  n_epoch: 20
  n_eval_epoch: 5
  gradient_clip: 1.0
  retrain: false