dataloader:
  name: ['earthquakes_jp']
model:
  act: ['relu']
  n_layers: [3]
  hid_dim: [128]
  inp_dim: 3
  out_dim: 1
  bias: true
trained_model:
  # name: ['auto-stpp', 'monte-carlo-stpp']
  name: ['monte-carlo-stpp']
  lr: 0.0004
  n_epoch: 50
  n_eval_epoch: 5
  retrain: true